GET http://localhost:3000/ping

###
POST http://localhost:3000/auth/login
###
POST http://localhost:3000/auth/registrar
Content-type: application/json

{
    "nome": "Barbeiro True",
    "email": "barber@empresa.com.br",
    "senha": "1233@fd",
    "telefone": "(18) 99999-9999",
    "barbeiro": true
}