GET http://localhost:3000/ping

###
POST http://localhost:3000/auth/login
###
POST http://localhost:3000/auth/registrar
Content-type: application/json

{
    "nome": "Tiago",
    "email": "ti@zmail.com.br",
    "senha": "222@222",
    "telefone": "(10) 99999-9999",
    "barbeiro": false
}
###
POST http://localhost:3000/auth/login
Content-type: application/json

{
    "email": "ti@zmail.com.br",
    "senha": "222@222"
}