GET http://localhost:3000/ping

###
POST http://localhost:3000/auth/login
###
POST http://localhost:3000/auth/registrar
Content-type: application/json

{
    "nome": "Rebeca",
    "email": "re@empresa.com.br",
    "senha": "2222@fd",
    "telefone": "(10) 99999-9999",
    "barbeiro": false
}